// <auto-generated />
using System;
using Marcos_Rosario_P2_AP1.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Marcos_Rosario_P2_AP1.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Marcos_Rosario_P2_AP1.Models.Ciudades", b =>
                {
                    b.Property<int>("CiudadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CiudadId"));

                    b.Property<double>("Monto")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CiudadId");

                    b.ToTable("Ciudades");

                    b.HasData(
                        new
                        {
                            CiudadId = 1,
                            Monto = 0.0,
                            Nombre = "Tenares"
                        },
                        new
                        {
                            CiudadId = 2,
                            Monto = 0.0,
                            Nombre = "San Fracisco de Macoris"
                        },
                        new
                        {
                            CiudadId = 3,
                            Monto = 0.0,
                            Nombre = "Santiago"
                        });
                });

            modelBuilder.Entity("Marcos_Rosario_P2_AP1.Models.Cursos", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoId"));

                    b.Property<string>("Asignatura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CiudadesCiudadId")
                        .HasColumnType("int");

                    b.Property<int>("Ciudadid")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<double>("Monto")
                        .HasColumnType("float");

                    b.HasKey("CursoId");

                    b.HasIndex("CiudadesCiudadId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Marcos_Rosario_P2_AP1.Models.CursosDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("DetalleId");

                    b.HasIndex("CiudadId");

                    b.HasIndex("CursoId");

                    b.ToTable("CursosDetalle");
                });

            modelBuilder.Entity("Marcos_Rosario_P2_AP1.Models.Cursos", b =>
                {
                    b.HasOne("Marcos_Rosario_P2_AP1.Models.Ciudades", "Ciudades")
                        .WithMany("Cursos")
                        .HasForeignKey("CiudadesCiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("Marcos_Rosario_P2_AP1.Models.CursosDetalle", b =>
                {
                    b.HasOne("Marcos_Rosario_P2_AP1.Models.Ciudades", "Ciudades")
                        .WithMany()
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marcos_Rosario_P2_AP1.Models.Cursos", "Cursos")
                        .WithMany("Detalles")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ciudades");

                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("Marcos_Rosario_P2_AP1.Models.Ciudades", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("Marcos_Rosario_P2_AP1.Models.Cursos", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
